#!/usr/bin/expect
puts "\n\n================================\n\n"
puts "\nTesting exit:  \n"
puts "\n\n================================\n\n"
spawn ./room.cgi
send "command=exit&inventory=10%2c10\r"
send "command=exit&inventory=10%2c10\r"
interact
puts "\n\n================================\n\n"
puts "\nTesting drop n: \n"
spawn ./room.cgi
puts "\n\n================================\n\n"
send "command=drop 2&inventory=10%2c10\r" 
send "command=drop 2&inventory=10%2c10\r"
interact
puts "\n\n================================\n\n"
puts "\nTesting refresh: \n"
puts "\n\n================================\n\n"
spawn ./room.cgi
send "command=refresh&inventory=10%2c10\r"
send "command=refresh&inventory=10%2c10\r"
interact
puts "\n\n================================\n\n"
puts "\nTesting Invalid command:  \n"
puts "\n\n================================\n\n"
spawn ./room.cgi
send "command=blargh&inventory=10%2c10\r"
send "command=blargh&inventory=10%2c10\r"
interact